language: cpp
compiler: 
    - gcc
notifications:
    email: false
before_install:
    - sudo apt-get update -qq -y
    - sudo apt-get install zlib1g-dev
    - sudo add-apt-repository ppa:staticfloat/julia-deps -y
    - sudo add-apt-repository ppa:staticfloat/julianightlies -y
    - sudo apt-get update -qq -y
    - sudo apt-get install patchelf gfortran llvm-3.2-dev libsuitesparse-dev libncurses5-dev libopenblas-dev liblapack-dev libarpack2-dev libfftw3-dev libgmp-dev libpcre3-dev libunwind7-dev libreadline-dev libdouble-conversion-dev libopenlibm-dev librmath-dev -y
    - sudo apt-get install julia
    - git config --global user.name "Dummy Travis User"
    - git config --global user.email "travis@example.net"
script:
    - julia -e 'versioninfo(); Pkg.init();'
    - mkdir -p ~/.julia/Distributions
    - cp -R ./* ~/.julia/Distributions/
    - julia ~/.julia/Distributions/test/Distributions.jl
    - julia ~/.julia/Distributions/test/Wisharts.jl
    - julia ~/.julia/Distributions/test/fit.jl
    - julia ~/.julia/Distributions/test/utils.jl
