name: UpdateRefs

on:
  schedule:
    - cron: '00 00 * * 00'
  workflow_dispatch:

jobs:
  UpdateRefs:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v5
        - uses: r-lib/actions/setup-r@v2
          with:
            r-version: '4'
        - uses: r-lib/actions/setup-renv@v2
          with:
            working-directory: 'test/refs'
        - name: Update renv
          run: renv::update()
          shell: Rscript {0}
          working-directory: test/ref
        - name: Check for changes of R environment
          id: check
          shell: bash
          run: |
            output=$(git diff --name-only -- test/ref)
            if [ "$output" != "" ]; then
                >&1 echo "The R environment was updated"
                echo "changed=true" >> "$GITHUB_OUTPUT"
            else
                echo "changed=false" >> "$GITHUB_OUTPUT"
            fi
        - name: Regenerate references
          if: steps.check.outputs.changed
          run: Rscript gendref.R
          working-directory: test/ref
        - name: Create pull request
          if: steps.check.outputs.changed
          uses: peter-evans/create-pull-request@7
          with:
            token: ${{ secrets.DOCUMENTER_KEY }}
            commit-message: "ðŸ¤– Automatic update of R references"
            title: "ðŸ¤– Automatic update of R references"
            body: |-
              This pull request updates all packages and references in the `test/ref` directory.
            delete-branch: true
            add-paths: test/ref
